version: '3.8'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3.5
    command: ["start-dev"]
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
volumes:
  keycloak_data:
